pub fn is_builtin(name: &str) -> bool {
    matches!(
        name,
        "Object"
            | "Array"
            | "String"
            | "Number"
            | "Boolean"
            | "Function"
            | "Math"
            | "Date"
            | "RegExp"
            | "JSON"
            | "console"
            | "parseInt"
            | "parseFloat"
            | "isNaN"
            | "isFinite"
            | "eval"
            | "undefined"
            | "NaN"
            | "Infinity"
            | "Error"
            | "TypeError"
            | "RangeError"
            | "SyntaxError"
            | "Symbol"
            | "Promise"
            | "Map"
            | "Set"
            | "WeakMap"
            | "WeakSet"
            | "Proxy"
            | "Reflect"
            | "ArrayBuffer"
            | "DataView"
            | "Int8Array"
            | "Uint8Array"
            | "Int16Array"
            | "Uint16Array"
            | "Int32Array"
            | "Uint32Array"
            | "Float32Array"
            | "Float64Array"
            | "SharedArrayBuffer"
            | "BigInt"
            | "TypedArray"
            | "Unint8ClampedArray"
            | "BigInt64Array"
            | "BigUint64Array"
            | "ReferenceError"
            | "EvalError"
            | "URIError"
            | "AggregateError"
            | "encodeURI"
            | "encodeURIComponent"
            | "decodeURI"
            | "decodeURIComponent"
            | "WeakRef"
            | "Uint8ClampedArray"
    )
}